name: smart_kitchen_mobile
description: Smart Kitchen mobile and web client
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  dio: ^5.8.0+1
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.3.0
  flutter_secure_storage: ^9.2.4
  get: ^4.7.2
  google_sign_in: ^6.2.2
  intl: any
  mobile_scanner: ^7.4.1
  mobx: ^2.5.0
  permission_handler: ^13.0.2
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  generate: true
